-- Create the layoffs table based on the immutable data model
CREATE TABLE IF NOT EXISTS layoffs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name TEXT NOT NULL,
    layoff_date DATE NOT NULL,
    employees_laid_off INTEGER,
    country TEXT NOT NULL,
    industry TEXT NOT NULL,
    source_url TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create index for faster querying
CREATE INDEX IF NOT EXISTS idx_layoffs_company_name ON layoffs(company_name);
CREATE INDEX IF NOT EXISTS idx_layoffs_date ON layoffs(layoff_date);
CREATE INDEX IF NOT EXISTS idx_layoffs_country ON layoffs(country);
CREATE INDEX IF NOT EXISTS idx_layoffs_industry ON layoffs(industry);
