-- Create the layoffs table based on the immutable data model
CREATE TABLE IF NOT EXISTS layoffs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name TEXT NOT NULL,
    layoff_date DATE NOT NULL,
    employees_laid_off INTEGER,
    country TEXT NOT NULL,
    industry TEXT NOT NULL,
    source_url TEXT NOT NULL UNIQUE,
    source_name TEXT DEFAULT 'Unknown' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create index for faster querying
CREATE INDEX IF NOT EXISTS idx_layoffs_company_name ON layoffs(company_name);
CREATE INDEX IF NOT EXISTS idx_layoffs_date ON layoffs(layoff_date);
CREATE INDEX IF NOT EXISTS idx_layoffs_country ON layoffs(country);
CREATE INDEX IF NOT EXISTS idx_layoffs_industry ON layoffs(industry);
CREATE INDEX IF NOT EXISTS idx_layoffs_source ON layoffs(source_name);

-- Community comments for peer context and discussion
CREATE TABLE IF NOT EXISTS layoff_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    layoff_id BIGINT NOT NULL REFERENCES layoffs(id) ON DELETE CASCADE,
    display_name TEXT NOT NULL DEFAULT 'Anonymous peer',
    comment_text TEXT NOT NULL,
    comment_kind TEXT NOT NULL DEFAULT 'general' CHECK (comment_kind IN ('general', 'helpful', 'question', 'correction', 'false_flag')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_layoff_comments_layoff_id ON layoff_comments(layoff_id);
CREATE INDEX IF NOT EXISTS idx_layoff_comments_created_at ON layoff_comments(created_at);
